In [ ]:
import numpy as np
import pandas as pd


In [ ]:
print(np.arange(10,30, 1.3))
print(np.linspace(10,30,20))

In [ ]:
print(np.zeros((5,2)))
print(np.ones((5,2))*3)
print(np.empty((5,2))) # empty i guess
print(np.eye(5)) # Identity

In [16]:
print(np.random.rand(3,4)) # Uniformly distributed
print(np.random.randn(3,4)) # Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
print(np.random.randint(1,50,100)) # randint (low, high, # of samples to be drawn)

[[0.97812017 0.37001454 0.59947841 0.34735002]
 [0.53168019 0.73993274 0.09037318 0.47080484]
 [0.65545467 0.50474849 0.45898385 0.8422673 ]]
[[ 0.70020484 -0.23065641 -0.34732281  0.07119859]
 [-0.24900574 -0.59237305  2.09817352 -0.02848252]
 [-0.67947091  1.57154965  0.60189514 -0.16284234]]
[37 12 31 23 14 43 45 37  9 34 30 28 33 49  5  4 31 13 11 15  3 21  7 30
 31 15 24 41 47 13 42 49 17 31 47  6 33 28  6  9 40  2 36 24 34 21 35 24
 36 34 31  4 18  4 18 40 42 41 17 23 10 16 13 29 17 22 20 10 33 24 13 34
 37 16 20 43 42 16 20 42  4 42 28 45  7 32 31 47 32 15 34  7 48 24 39 24
 16 48  4 17]


In [21]:
a = np.random.randint(1,50,100)
print('a: ', a)
print(max(a))
print(a.argmax()) # index of max(a)

a:  [19  5  1 35 15 42 35 41 33  5 22 14 25 11  9 14 32 14 37  7 23 28  7 24
 18 15 14  1 41 43 44 45 30 21 40  6 33  5 44 10  5 39 32 22 27 44 15 43
 22 10 26 11 10 46 41 40 17 23 14 31 46 45  2 48 43 48 34 39 22 21 15 17
 19 23 16  8 48 23 47 22 19  8 49 44 36 29 49 43 48  1 28 15 48 39 39  3
 39 35 35 10]
49
82


In [24]:
arr = np.arange(0,11)
print("Array:",arr)
print("Element at 7th index is:", arr[7])
print("Elements from 3rd to 5th index are:", arr[3:6])
print("Elements up to 4th index are:", arr[:4])
print("Elements from last backwards are:", arr[::-1])
print("3 Elements from last backwards are:", arr[-1:-6:-2])

arr = np.arange(0,21,2)
print("New array:",arr)
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Array: [ 0  1  2  3  4  5  6  7  8  9 10]
Element at 7th index is: 7
Elements from 3rd to 5th index are: [3 4 5]
Elements up to 4th index are: [0 1 2 3]
Elements from last backwards are: [10  9  8  7  6  5  4  3  2  1  0]
3 Elements from last backwards are: [10  8  6]
New array: [ 0  2  4  6  8 10 12 14 16 18 20]
Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [31]:
mat = np.array(np.random.randint(10,100,15)).reshape(3,5)
print('mat: ', mat)
print(mat[0:2,[1,3]])
print(mat[mat>20])


mat:  [[41 56 81 75 43]
 [46 90 81 79 38]
 [99 36 80 88 63]]
[[56 75]
 [90 79]]
[41 56 81 75 43 46 90 81 79 38 99 36 80 88 63]
