In [2]:
import tensorflow as tf
print(tf.__version__)

2.7.0


In [4]:
a = tf.Variable('blah',tf.string)
b = tf.Variable(5,tf.int16)
c = tf.Variable(3.3453,tf.float64)

In [9]:
r1 = tf.Variable([2,4,5],tf.int16)
r2 = tf.Variable([[2.2,3.4],[1.1,3.4]],tf.float64)
r2.shape

TensorShape([2, 2])

In [13]:
t1 = tf.ones([1,2,3])
print('t1: ', t1)
t2 = tf.reshape(t1,[3,2,1])
print('t2: ', t2)
t3 = tf.reshape(t2,[3,-1])
print('t3: ', t3)

t1:  tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
t2:  tf.Tensor(
[[[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]], shape=(3, 2, 1), dtype=float32)
t3:  tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [ ]:
# with tf.compat.V1.Session() as sess:
#     tensor.eval()